runtime: php
env: flex

manual_scaling:
  instances: 1

resources:
  memory_gb: 1

runtime_config:
  document_root: public

env_variables:
  APP_ENV: production
  APP_KEY: your-app-key
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  QUEUE_DRIVER: sync
